window.productsData = {
  "categories": {
    "tents": {
      "name": "Tents & Shelters",
      "featureImage": "images/camping_tents/camping_tents_feature.jpg",
      "description": "Prepare for your upcoming camping trip by upgrading your tent or shelter! Create a Modern-style campsite with designated spaces for cooking, sleeping, and gathering.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"],
        "capacity": ["1 Person", "2 Person", "4 Person", "6+ Person"]
      }
    },
    "sleeping-bags": {
      "name": "Sleeping Bags",
      "featureImage": "images/Sleeping_bag/Sleeping_bag_1.png",
      "description": "Stay warm and comfortable on every adventure. Our sleeping bags are designed for all seasons, from summer backpacking to winter base camps.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"],
        "capacity": ["1 Person", "2 Person"]
      }
    },
    "camping-chairs": {
      "name": "Camping Chairs",
      "featureImage": "images/camping_chair/camping_chair_1.png",
      "description": "Relax in style at your campsite. Our camping chairs combine comfort, durability, and portability so you can unwind anywhere in the great outdoors.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"]
      }
    },
    "camping-lamps": {
      "name": "Lanterns & Lamps",
      "featureImage": "images/camping_lamp/camping_lamp_1.jpg",
      "description": "Light up your campsite with our range of lanterns and lamps. From compact headlamps to powerful base camp lanterns, we have the right light for every situation.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"]
      }
    },
    "camping-stoves": {
      "name": "Camping Stoves",
      "featureImage": "images/camping_stove/camping_stove.png",
      "description": "Cook delicious meals in the wilderness with our high-performance camping stoves. Lightweight, efficient, and built to handle any outdoor cooking challenge.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"]
      }
    },
    "cooking-sets": {
      "name": "Camp Cooking Sets",
      "featureImage": "images/camp_cooking_set/camping_cooking_set.jpg",
      "description": "Everything you need to cook like a pro at camp. Our cooking sets include pots, pans, utensils, and more — all designed for the outdoors.",
      "filters": {
        "price": ["Under $200", "$200 - $400", "$400 - $600", "Over $600"],
        "size": ["Small", "Medium", "Large"]
      }
    }
  },
  "products": [
    { "id": "alpha-breeze-tent", "name": "Alpha Breeze Tent", "category": "tents", "price": 349.95, "image": "images/camping_tents/Camping_tent_1.png", "description": "2-4 Person Waterproof Shelter", "capacity": "4P", "details": "Spacious weather-resistant shelter perfect for family camping trips.", "included": "Tent body, poles, pegs, ropes, carry bag and rain cover.", "specs": "Capacity: 4P<br>Weight: 8.5kg<br>Material: Waterproof polyester", "features": "Easy setup, wind resistant, spacious ventilation and premium frame.", "hasDetailPage": true, "detailPageUrl": "product.html?id=alpha-breeze-tent", "related": ["compact-dome-tent", "family-shelter", "solo-trek-tent"] },
    { "id": "compact-dome-tent", "name": "Compact Dome Tent", "category": "tents", "price": 249.95, "image": "images/camping_tents/Camping_tent_2.png", "description": "Lightweight 2-Person Camping Tent", "capacity": "2P", "details": "Easy-pitch dome tent with a lightweight aluminum frame, ideal for weekend trips.", "included": "Tent body, poles, pegs, carry bag.", "specs": "Capacity: 2P<br>Weight: 3.2kg<br>Material: Ripstop nylon", "features": "Quick pitch, mesh inner for ventilation, waterproof fly.", "hasDetailPage": true, "detailPageUrl": "product.html?id=compact-dome-tent", "related": ["alpha-breeze-tent", "solo-trek-tent", "explorer-tent"] },
    { "id": "family-shelter", "name": "Family Shelter", "category": "tents", "price": 499.95, "image": "images/camping_tents/Camping_tent_3.png", "description": "Large Tent for Family Trips", "capacity": "6P", "details": "Roomy 6-person family tent with two separate sleeping rooms and a central living area.", "included": "Tent body, divider, poles, pegs, carry bag.", "specs": "Capacity: 6P<br>Weight: 12kg<br>Material: Polyester 190T", "features": "Two rooms, large windows, e-cable port, dark rest technology.", "hasDetailPage": true, "detailPageUrl": "product.html?id=family-shelter", "related": ["alpha-breeze-tent", "compact-dome-tent", "explorer-tent"] },
    { "id": "solo-trek-tent", "name": "Solo Trek Tent", "category": "tents", "price": 189.95, "image": "images/camping_tents/Camping_tent_4.png", "description": "Minimal 1-Person Hiking Shelter", "capacity": "1P", "details": "Ultra-compact single-person tent designed for fast and light hiking adventures.", "included": "Tent, poles, pegs, stuff sack.", "specs": "Capacity: 1P<br>Weight: 1.5kg<br>Material: Silnylon", "features": "Freestanding, single-wall design, vestibule storage.", "hasDetailPage": true, "detailPageUrl": "product.html?id=solo-trek-tent", "related": ["compact-dome-tent", "explorer-tent", "alpha-breeze-tent"] },
    { "id": "explorer-tent", "name": "Explorer Tent", "category": "tents", "price": 289.95, "image": "images/camping_tents/Camping_tent_5.png", "description": "All-Weather 3-Person Protection", "capacity": "3P", "details": "Versatile 3-season tent built for explorers who face unpredictable weather.", "included": "Tent, poles, pegs, guylines, carry bag.", "specs": "Capacity: 3P<br>Weight: 5.1kg<br>Material: 75D polyester", "features": "Storm-rated, geodesic poles, two vestibules, reflective guylines.", "hasDetailPage": true, "detailPageUrl": "product.html?id=explorer-tent", "related": ["alpha-breeze-tent", "family-shelter", "compact-dome-tent"] },
    { "id": "land-nest-shelter", "name": "Land Nest Shelter", "category": "tents", "price": 999.95, "image": "images/camping_tents/Camping_tent_3.png", "description": "Premium Luxury Basecamp Shelter", "capacity": "6P", "details": "The ultimate luxury basecamp shelter with a spacious footprint and premium materials.", "included": "Shelter, inner tent, poles, pegs, carpet, carry bag.", "specs": "Capacity: 6P<br>Weight: 18kg<br>Material: 300D canvas", "features": "Standing height, wood stove port, blackout fabric, multiple windows.", "hasDetailPage": true, "detailPageUrl": "product.html?id=land-nest-shelter", "related": ["family-shelter", "alpha-breeze-tent", "explorer-tent"] },
    { "id": "trailblazer-sleeping-bag", "name": "Trailblazer Sleeping Bag", "category": "sleeping-bags", "price": 189.95, "image": "images/Sleeping_bag/Sleeping_bag_1.png", "description": "3-Season Lightweight Bag", "capacity": "1P", "details": "Lightweight 3-season sleeping bag rated to 10°C, perfect for backpacking and hiking trips.", "included": "Sleeping bag and compression stuff sack.", "specs": "Temperature Rating: 10°C<br>Weight: 1.2kg<br>Fill: Synthetic insulation", "features": "Mummy cut, anti-snag zipper, internal pocket, hood cinch.", "hasDetailPage": true, "detailPageUrl": "product.html?id=trailblazer-sleeping-bag", "related": ["arctic-pro-sleeping-bag", "summit-duo-bag", "ultralight-sleeping-bag"] },
    { "id": "arctic-pro-sleeping-bag", "name": "Arctic Pro Sleeping Bag", "category": "sleeping-bags", "price": 329.95, "image": "images/Sleeping_bag/Sleeping_bag_2.png", "description": "Winter Rated -15°C Bag", "capacity": "1P", "details": "Heavy-duty winter sleeping bag designed for extreme cold conditions and alpine expeditions.", "included": "Sleeping bag, compression sack, storage bag.", "specs": "Temperature Rating: -15°C<br>Weight: 2.1kg<br>Fill: 800-fill down", "features": "Draft collar, insulated hood, anti-snag YKK zipper, water-resistant shell.", "hasDetailPage": true, "detailPageUrl": "product.html?id=arctic-pro-sleeping-bag", "related": ["trailblazer-sleeping-bag", "down-pro-sleeping-bag", "ultralight-sleeping-bag"] },
    { "id": "summit-duo-bag", "name": "Summit Duo Sleeping Bag", "category": "sleeping-bags", "price": 259.95, "image": "images/Sleeping_bag/Sleeping_bag_3.png", "description": "Double Sleeping Bag for Couples", "capacity": "2P", "details": "Spacious double sleeping bag perfect for couples who want to stay cozy together under the stars.", "included": "Double sleeping bag, stuff sack, pillow pockets.", "specs": "Temperature Rating: 5°C<br>Weight: 3.2kg<br>Fill: Synthetic blend", "features": "Two-way zippers, can split into two singles, integrated pillow pockets.", "hasDetailPage": true, "detailPageUrl": "product.html?id=summit-duo-bag", "related": ["trailblazer-sleeping-bag", "arctic-pro-sleeping-bag", "ultralight-sleeping-bag"] },
    { "id": "ultralight-sleeping-bag", "name": "Ultralight Sleeping Bag", "category": "sleeping-bags", "price": 149.95, "image": "images/Sleeping_bag/Sleeping_bag_4.png", "description": "Compact 500g Backpacking Bag", "capacity": "1P", "details": "Ultra-compact and lightweight sleeping bag designed for minimalist backpackers and thru-hikers.", "included": "Sleeping bag, ultra-light stuff sack.", "specs": "Temperature Rating: 15°C<br>Weight: 0.5kg<br>Fill: Premium down", "features": "Ultralight fabric, minimal design, packs to size of water bottle.", "hasDetailPage": true, "detailPageUrl": "product.html?id=ultralight-sleeping-bag", "related": ["trailblazer-sleeping-bag", "arctic-pro-sleeping-bag", "kids-sleeping-bag"] },
    { "id": "kids-sleeping-bag", "name": "Kids Adventure Bag", "category": "sleeping-bags", "price": 99.95, "image": "images/Sleeping_bag/Sleeping_bag_5.png", "description": "Cozy Bag for Young Campers", "capacity": "1P", "details": "Fun and comfortable sleeping bag designed specifically for kids, with room to grow.", "included": "Sleeping bag, stuff sack, glow-in-the-dark zipper pull.", "specs": "Temperature Rating: 10°C<br>Weight: 0.9kg<br>Fill: Synthetic", "features": "Grows with your child, fun colors, easy-zip design, machine washable.", "hasDetailPage": true, "detailPageUrl": "product.html?id=kids-sleeping-bag", "related": ["trailblazer-sleeping-bag", "ultralight-sleeping-bag", "down-pro-sleeping-bag"] },
    { "id": "down-pro-sleeping-bag", "name": "Down Pro Sleeping Bag", "category": "sleeping-bags", "price": 449.95, "image": "images/Sleeping_bag/Sleeping_bag_1.png", "description": "Premium Goose Down Fill Bag", "capacity": "1P", "details": "Top-of-the-line sleeping bag with premium 900-fill goose down for ultimate warmth-to-weight ratio.", "included": "Sleeping bag, premium compression sack, storage bag, repair kit.", "specs": "Temperature Rating: -10°C<br>Weight: 1.1kg<br>Fill: 900-fill goose down", "features": "Water-resistant down, draft tubes, contoured hood, premium YKK zippers.", "hasDetailPage": true, "detailPageUrl": "product.html?id=down-pro-sleeping-bag", "related": ["arctic-pro-sleeping-bag", "trailblazer-sleeping-bag", "ultralight-sleeping-bag"] },
    { "id": "trail-rest-chair", "name": "Trail Rest Chair", "category": "camping-chairs", "price": 129.95, "image": "images/camping_chair/camping_chair_1.png", "description": "Lightweight Folding Camp Chair", "details": "Compact and lightweight folding chair with a sturdy aluminum frame, perfect for any campsite.", "included": "Chair and carry bag.", "specs": "Weight: 1.8kg<br>Capacity: 120kg<br>Material: 600D Oxford fabric", "features": "Cup holder, side pocket, anti-sink feet, folds flat.", "hasDetailPage": true, "detailPageUrl": "product.html?id=trail-rest-chair", "related": ["summit-rocker-chair", "low-rider-chair", "directors-chair"] },
    { "id": "summit-rocker-chair", "name": "Summit Rocker Chair", "category": "camping-chairs", "price": 199.95, "image": "images/camping_chair/camping_chair_2.png", "description": "Rocking Camp Chair with Armrests", "details": "Innovative rocking camp chair that brings comfort to a whole new level at your campsite.", "included": "Rocking chair, carry bag, cup holder.", "specs": "Weight: 3.2kg<br>Capacity: 135kg<br>Material: Heavy-duty polyester", "features": "Smooth rocking motion, padded armrests, built-in lumbar support, cup holder.", "hasDetailPage": true, "detailPageUrl": "product.html?id=summit-rocker-chair", "related": ["trail-rest-chair", "xl-padded-chair", "directors-chair"] },
    { "id": "low-rider-chair", "name": "Low Rider Beach Chair", "category": "camping-chairs", "price": 89.95, "image": "images/camping_chair/camping_chair_3.png", "description": "Low-Profile Lounging Chair", "details": "Low-to-the-ground chair perfect for beach days, concerts, and relaxed camping.", "included": "Chair, carry strap.", "specs": "Weight: 1.2kg<br>Capacity: 100kg<br>Material: Breathable mesh", "features": "Low profile, breathable mesh back, lightweight, easy carry strap.", "hasDetailPage": true, "detailPageUrl": "product.html?id=low-rider-chair", "related": ["trail-rest-chair", "kids-camp-chair", "summit-rocker-chair"] },
    { "id": "directors-chair", "name": "Director's Camp Chair", "category": "camping-chairs", "price": 159.95, "image": "images/camping_chair/camping_chair_4.png", "description": "Tall Chair with Side Table", "details": "Classic director's style chair with integrated side table for ultimate campsite convenience.", "included": "Chair, side table, carry bag.", "specs": "Weight: 4.1kg<br>Capacity: 140kg<br>Material: Canvas and wood", "features": "Folding side table, tall back support, premium wood frame, cup holder.", "hasDetailPage": true, "detailPageUrl": "product.html?id=directors-chair", "related": ["trail-rest-chair", "summit-rocker-chair", "xl-padded-chair"] },
    { "id": "kids-camp-chair", "name": "Kids Camp Chair", "category": "camping-chairs", "price": 59.95, "image": "images/camping_chair/camping_chair_5.png", "description": "Small Chair for Young Campers", "details": "Perfectly sized camping chair for kids, with fun colors and easy folding design.", "included": "Chair, carry bag with shoulder strap.", "specs": "Weight: 0.9kg<br>Capacity: 50kg<br>Material: Durable nylon", "features": "Kid-sized, bright colors, easy fold, cup holder, safety tested.", "hasDetailPage": true, "detailPageUrl": "product.html?id=kids-camp-chair", "related": ["trail-rest-chair", "low-rider-chair", "summit-rocker-chair"] },
    { "id": "xl-padded-chair", "name": "XL Padded Camp Chair", "category": "camping-chairs", "price": 229.95, "image": "images/camping_chair/camping_chair_1.png", "description": "Extra Wide Padded Comfort Chair", "details": "Extra-large camping chair with thick padding and wide seat for maximum comfort.", "included": "XL chair, padded carry bag, cup holder.", "specs": "Weight: 5.2kg<br>Capacity: 180kg<br>Material: Padded polyester", "features": "Extra-wide seat, thick padding, reinforced frame, dual cup holders, headrest.", "hasDetailPage": true, "detailPageUrl": "product.html?id=xl-padded-chair", "related": ["summit-rocker-chair", "directors-chair", "trail-rest-chair"] },
    { "id": "nova-lantern", "name": "Nova LED Lantern", "category": "camping-lamps", "price": 79.95, "image": "images/camping_lamp/camping_lamp_1.jpg", "description": "360° Bright LED Camp Lantern", "details": "Powerful 500-lumen LED lantern with 3 brightness modes and a collapsible design for easy packing.", "included": "Lantern, USB charging cable, carry pouch.", "specs": "Lumens: 500lm<br>Battery: 4000mAh<br>Runtime: Up to 12 hours", "features": "3 brightness modes, USB rechargeable, waterproof IPX4, collapsible.", "hasDetailPage": true, "detailPageUrl": "product.html?id=nova-lantern", "related": ["solar-camp-lantern", "headlamp-pro", "string-lights"] },
    { "id": "solar-camp-lantern", "name": "Solar Camp Lantern", "category": "camping-lamps", "price": 99.95, "image": "images/camping_lamp/camping_lamp_2.png", "description": "Solar + USB Rechargeable Lantern", "details": "Eco-friendly lantern with solar panel and USB charging options for sustainable camping.", "included": "Lantern, USB cable, carabiner clip.", "specs": "Lumens: 400lm<br>Battery: 5000mAh<br>Solar charge: 8-10 hours", "features": "Solar panel, power bank function, 4 light modes, emergency SOS flash.", "hasDetailPage": true, "detailPageUrl": "product.html?id=solar-camp-lantern", "related": ["nova-lantern", "headlamp-pro", "torch-flashlight"] },
    { "id": "headlamp-pro", "name": "Headlamp Pro 300", "category": "camping-lamps", "price": 59.95, "image": "images/camping_lamp/camping_lamp_3.png", "description": "300 Lumen Hands-Free Headlamp", "details": "Powerful hands-free headlamp perfect for night hiking, cooking, and camp tasks.", "included": "Headlamp, adjustable strap, USB cable.", "specs": "Lumens: 300lm<br>Battery: Rechargeable<br>Runtime: 6 hours", "features": "Adjustable beam angle, red light mode, motion sensor, lightweight design.", "hasDetailPage": true, "detailPageUrl": "product.html?id=headlamp-pro", "related": ["nova-lantern", "torch-flashlight", "solar-camp-lantern"] },
    { "id": "string-lights", "name": "Camp String Lights", "category": "camping-lamps", "price": 44.95, "image": "images/camping_lamp/camping_lamp_4.png", "description": "10m Waterproof LED String Lights", "details": "Create ambiance at your campsite with these waterproof LED string lights.", "included": "10m string lights, USB power adapter, storage bag.", "specs": "Length: 10m<br>LEDs: 50 bulbs<br>Power: USB or battery", "features": "Waterproof, 8 lighting modes, timer function, dimmable.", "hasDetailPage": true, "detailPageUrl": "product.html?id=string-lights", "related": ["nova-lantern", "solar-camp-lantern", "candle-lantern"] },
    { "id": "candle-lantern", "name": "Classic Candle Lantern", "category": "camping-lamps", "price": 34.95, "image": "images/camping_lamp/camping_lamp_5.png", "description": "Traditional Candle-Style Lantern", "details": "Classic candle lantern for a traditional camping experience with warm ambient light.", "included": "Lantern, glass chimney, 3 candles.", "specs": "Height: 25cm<br>Material: Steel and glass<br>Burn time: 8 hours per candle", "features": "Wind-resistant glass, foldable handle, classic design, replacement candles available.", "hasDetailPage": true, "detailPageUrl": "product.html?id=candle-lantern", "related": ["nova-lantern", "string-lights", "solar-camp-lantern"] },
    { "id": "torch-flashlight", "name": "Tactical Torch Flashlight", "category": "camping-lamps", "price": 49.95, "image": "images/camping_lamp/camping_lamp_1.jpg", "description": "1000 Lumen Waterproof Torch", "details": "High-powered tactical flashlight with zoom function and multiple brightness modes.", "included": "Flashlight, rechargeable battery, USB cable, holster.", "specs": "Lumens: 1000lm<br>Battery: 18650 rechargeable<br>Range: 300m", "features": "Zoom focus, 5 modes, aircraft-grade aluminum, waterproof IPX6.", "hasDetailPage": true, "detailPageUrl": "product.html?id=torch-flashlight", "related": ["headlamp-pro", "nova-lantern", "solar-camp-lantern"] },
    { "id": "peak-stove", "name": "Peak Backpacking Stove", "category": "camping-stoves", "price": 89.95, "image": "images/camping_stove/camping_stove.png", "description": "Ultra-Compact Gas Canister Stove", "details": "Ultralight backpacking stove that screws directly onto standard gas canisters. Boils 1L in under 3 minutes.", "included": "Stove burner, piezo igniter, carry case.", "specs": "Weight: 85g<br>Output: 2700W<br>Boil Time: 2.5 min/L", "features": "Piezo ignition, foldable pot supports, wind shield, simmer control.", "hasDetailPage": true, "detailPageUrl": "product.html?id=peak-stove", "related": ["base-camp-stove", "two-burner-stove", "wood-gasifier-stove"] },
    { "id": "base-camp-stove", "name": "Base Camp Stove", "category": "camping-stoves", "price": 149.95, "image": "images/camping_stove/camping_stove_2.png", "description": "High-Output 3-Leg Camp Stove", "details": "Powerful three-leg camp stove designed for base camp cooking and group meals.", "included": "Stove, wind shield, carry bag.", "specs": "Weight: 1.2kg<br>Output: 3500W<br>Fuel: Propane/butane", "features": "Stable 3-leg design, adjustable flame, wind-resistant, fits large pots.", "hasDetailPage": true, "detailPageUrl": "product.html?id=base-camp-stove", "related": ["peak-stove", "two-burner-stove", "windmaster-stove"] },
    { "id": "two-burner-stove", "name": "Dual Burner Propane Stove", "category": "camping-stoves", "price": 199.95, "image": "images/camping_stove/camping_stove_3.png", "description": "Two-Burner Family Camp Stove", "details": "Full-featured two-burner stove perfect for family camping and car camping.", "included": "Stove, wind guards, propane hose, carry case.", "specs": "Weight: 4.5kg<br>Output: 2x 3000W<br>Fuel: Propane", "features": "Independent burner controls, wind guards, matchless ignition, fits 12-inch pans.", "hasDetailPage": true, "detailPageUrl": "product.html?id=two-burner-stove", "related": ["base-camp-stove", "peak-stove", "auto-ignite-stove"] },
    { "id": "wood-gasifier-stove", "name": "Wood Gasifier Stove", "category": "camping-stoves", "price": 119.95, "image": "images/camping_stove/camping_stove_4.png", "description": "Burn Twigs — No Gas Needed", "details": "Innovative wood-burning stove that uses twigs and biomass, eliminating the need for fuel canisters.", "included": "Stove body, ash tray, carry bag.", "specs": "Weight: 0.9kg<br>Fuel: Wood/biomass<br>Boil time: 4-5 min/L", "features": "No fuel needed, secondary combustion, USB fan option, eco-friendly.", "hasDetailPage": true, "detailPageUrl": "product.html?id=wood-gasifier-stove", "related": ["peak-stove", "base-camp-stove", "windmaster-stove"] },
    { "id": "windmaster-stove", "name": "Windmaster Stove", "category": "camping-stoves", "price": 109.95, "image": "images/camping_stove/camping_stove_5.png", "description": "4-Flex Wind-Resistant Burner", "details": "Advanced stove with 4-flex pot supports and exceptional wind resistance for alpine conditions.", "included": "Stove, pot supports, wind screen, case.", "specs": "Weight: 110g<br>Output: 2800W<br>Boil time: 2.8 min/L", "features": "4-flex pot supports, concave burner head, wind-resistant, precise simmer.", "hasDetailPage": true, "detailPageUrl": "product.html?id=windmaster-stove", "related": ["peak-stove", "base-camp-stove", "auto-ignite-stove"] },
    { "id": "auto-ignite-stove", "name": "Auto-Ignite Camp Stove", "category": "camping-stoves", "price": 79.95, "image": "images/camping_stove/camping_stove.png", "description": "Push-Button Ignition Stove", "details": "Convenient camp stove with automatic push-button ignition for hassle-free lighting.", "included": "Stove, igniter, carry pouch.", "specs": "Weight: 95g<br>Output: 2600W<br>Fuel: Butane/propane", "features": "Auto-ignition, compact design, adjustable flame, folds flat.", "hasDetailPage": true, "detailPageUrl": "product.html?id=auto-ignite-stove", "related": ["peak-stove", "windmaster-stove", "two-burner-stove"] },
    { "id": "trail-cook-set", "name": "Trail Cook Set", "category": "cooking-sets", "price": 69.95, "image": "images/camp_cooking_set/camping_cooking_set.jpg", "description": "4-Piece Lightweight Cookware Set", "details": "Compact 4-piece anodized aluminum cookware set designed for backpacking and camping.", "included": "2 pots, 1 frying pan, 1 lid, mesh carry bag.", "specs": "Material: Hard-anodized aluminum<br>Pieces: 4<br>Weight: 680g", "features": "Non-stick coating, foldable handles, nesting design, dishwasher safe.", "hasDetailPage": true, "detailPageUrl": "product.html?id=trail-cook-set", "related": ["cast-iron-skillet", "camp-utensil-set", "camp-coffee-maker"] },
    { "id": "cast-iron-skillet", "name": "Cast Iron Camp Skillet", "category": "cooking-sets", "price": 89.95, "image": "images/camp_cooking_set/camping_cookware_set.jpg", "description": "Pre-Seasoned 10\" Cast Iron Pan", "details": "Traditional cast iron skillet perfect for campfire cooking and Dutch oven meals.", "included": "10-inch skillet, silicone handle cover, storage bag.", "specs": "Material: Cast iron<br>Size: 10 inches<br>Weight: 2.3kg", "features": "Pre-seasoned, even heat distribution, oven safe, lifetime durability.", "hasDetailPage": true, "detailPageUrl": "product.html?id=cast-iron-skillet", "related": ["trail-cook-set", "camp-utensil-set", "camp-plate-set"] },
    { "id": "camp-utensil-set", "name": "Camp Utensil Set", "category": "cooking-sets", "price": 29.95, "image": "images/camp_cooking_set/camping_cup_1.jpg", "description": "10-Piece Stainless Utensil Kit", "details": "Complete utensil set with everything you need for camp cooking and dining.", "included": "Spatula, ladle, tongs, knife, fork, spoon, cutting board, bottle opener, case.", "specs": "Material: Stainless steel<br>Pieces: 10<br>Weight: 450g", "features": "Compact case, rust-resistant, dishwasher safe, includes cutting board.", "hasDetailPage": true, "detailPageUrl": "product.html?id=camp-utensil-set", "related": ["trail-cook-set", "cast-iron-skillet", "camp-coffee-maker"] },
    { "id": "camp-coffee-cup", "name": "Camp Coffee Cup", "category": "cooking-sets", "price": 49.95, "image": "images/camp_cooking_set/camping_cup_2.jpg", "description": "Portable Pour-Over Coffee Set", "details": "Enjoy barista-quality coffee at camp with this portable pour-over coffee Cup.", "included": "Pour-over dripper, carafe, reusable filter, carry case.", "specs": "Capacity: 600ml<br>Material: Stainless steel<br>Weight: 320g", "features": "Reusable filter, collapsible design, heat-resistant carafe, easy to clean.", "hasDetailPage": true, "detailPageUrl": "product.html?id=camp-coffee-cup", "related": ["camp-water-bottle", "camp-utensil-set", "trail-cook-set"] },
    { "id": "camp-water-bottle", "name": "Insulated Water Bottle", "category": "cooking-sets", "price": 39.95, "image": "images/camp_cooking_set/camping_water_bottle.jpg", "description": "1L Double-Wall Stainless Bottle", "details": "Keep drinks cold for 24 hours or hot for 12 hours with this insulated water bottle.", "included": "1L bottle, leak-proof lid, carabiner clip.", "specs": "Capacity: 1L<br>Material: Stainless steel<br>Insulation: Double-wall vacuum", "features": "24hr cold / 12hr hot, leak-proof, BPA-free, wide mouth opening.", "hasDetailPage": true, "detailPageUrl": "product.html?id=camp-water-bottle", "related": ["camp-coffee-maker", "camp-utensil-set", "camp-plate-set"] },
    { "id": "camp-coffee-cup2", "name": "Insulated Coffee Cup", "category": "cooking-sets", "price": 34.95, "image": "images/camp_cooking_set/camping_cup_3.jpg", "description": "Classic Enamel Dining Set for 2", "details": "Enjoy your coffe wih hot temperature at any time", "included": "2 mugs, mesh storage bag.", "specs": "Material: Enamel-coated steel<br>Set: For 2 people<br>Weight: 1.1kg", "features": "Classic design, chip-resistant, easy to clean, campfire safe.", "hasDetailPage": true, "detailPageUrl": "product.html?id=camp-coffee-cup2", "related": ["trail-cook-set", "cast-iron-skillet", "camp-utensil-set"] }
  ]
};
